name: Convincible
seo:
  title: Marketing and Communications
  description: In this busy and noisy modern world, we get your message through, by
    making it clear, creative and compelling.
  image: 
  separator: "Â·"
  suffix: Cambridge, UK
language: en
copyright: Convincible is a Sole Tradership owned and managed by Virgil Ierubino.
social_profiles:
- type: twitter
  link: http://twitter.com/BeConvincible
- type: facebook
  link: http://fb.me/Convincible